-- =====================================================================
-- GitHubble PostgreSQL schema
-- - PostgreSQL 18 + pgvector 0.8.2
-- - 현재 애플리케이션 설정: ddl-auto=update + spring.sql.init.mode=always
--                + spring.jpa.defer-datasource-initialization=true
-- - JPA Entity와 수동 인덱스/pgvector 컬럼의 초기 스키마 기준.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =====================================================================
-- Auth / Profile
-- =====================================================================

CREATE TABLE IF NOT EXISTS app_user (
    app_user_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_uuid       uuid         NOT NULL UNIQUE,
    github_id           bigint       NOT NULL UNIQUE,
    username            varchar(255),
    email               varchar(255),
    github_access_token varchar(255),
    avatar_url          varchar(255),
    is_deleted          boolean      NOT NULL,
    created_at          timestamp,
    updated_at          timestamp
);

CREATE TABLE IF NOT EXISTS github_profile (
    gitprofile_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appuser_id             bigint,
    username               varchar(255),
    name                   varchar(255),
    github_avatar_url      varchar(255),
    type                   varchar(255),
    company                varchar(255),
    blog                   varchar(255),
    location               varchar(255),
    email                  varchar(255),
    bio                    varchar(255),
    public_repos_count     integer,
    created_at             timestamp,
    updated_at             timestamp,
    commit_count_this_year smallint,
    gitprofile_uuid        varchar(255) NOT NULL UNIQUE
);

-- =====================================================================
-- GitHub repository cache
-- =====================================================================

CREATE TABLE IF NOT EXISTS github_repository (
    repo_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_repo_id    bigint UNIQUE,
    owner_login       varchar(255) NOT NULL,
    repo_name         varchar(255) NOT NULL,
    default_branch    varchar(255),
    description       text,
    is_private        boolean      NOT NULL,
    html_url          text,
    last_synced_at    timestamp,
    created_at        timestamp    NOT NULL,
    updated_at        timestamp    NOT NULL,
    repo_uuid         uuid         NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS github_repository_tree_cache (
    tree_cache_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id           bigint       NOT NULL REFERENCES github_repository (repo_id),
    ref               varchar(255) NOT NULL,
    tree_sha          varchar(64),
    truncated         boolean      NOT NULL,
    tree_json         text         NOT NULL,
    fetched_at        timestamp    NOT NULL,
    CONSTRAINT uk_github_repository_tree_cache_repo_ref UNIQUE (repo_id, ref)
);

CREATE TABLE IF NOT EXISTS github_file_content_cache (
    file_content_cache_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id                 bigint       NOT NULL REFERENCES github_repository (repo_id),
    ref                     varchar(255) NOT NULL,
    path                    text         NOT NULL,
    file_name               varchar(255),
    sha                     varchar(64)  NOT NULL,
    type                    varchar(30)  NOT NULL,
    size                    bigint,
    encoding                varchar(50),
    content                 text,
    content_available       boolean      NOT NULL,
    is_binary               boolean      NOT NULL,
    unavailable_reason      varchar(50),
    html_url                text,
    fetched_at              timestamp    NOT NULL,
    last_accessed_at        timestamp    NOT NULL,
    CONSTRAINT uk_github_file_content_cache_repo_ref_path UNIQUE (repo_id, ref, path)
);

-- =====================================================================
-- GraphRAG pgvector
-- =====================================================================

CREATE TABLE IF NOT EXISTS graphrag_embeddings (
    id             uuid          PRIMARY KEY,
    arch_id        varchar(255)  NOT NULL,
    kind           varchar(32)   NOT NULL,
    ref_id         varchar(512)  NOT NULL,
    label          varchar(512),
    content        text          NOT NULL,

    -- node 전용
    node_id        varchar(512),
    node_type      varchar(128),
    description    text,
    path           text,

    -- edge 전용
    from_node_id   varchar(512),
    to_node_id     varchar(512),

    -- vector 및 메타데이터
    embedding      vector(3072)  NOT NULL,
    created_at     timestamp     NOT NULL DEFAULT now()
);

-- arch_id + kind: 검색·삭제 경로 모두의 첫 필터.
CREATE INDEX IF NOT EXISTS idx_embedding_arch_kind
    ON graphrag_embeddings (arch_id, kind);

-- ref_id: 디버그·하이드레이션 역방향 조회.
CREATE INDEX IF NOT EXISTS idx_embedding_ref_id
    ON graphrag_embeddings (ref_id);

-- 참고: vector 컬럼의 HNSW/IVFFlat 은 vector(2000) 상한 때문에 3072차원에서
-- 직접 생성 불가. 초기에는 arch_id 필터로 후보를 축소 후 플랫 스캔(<=>) 으로 Top-K.
-- 향후 halfvec(3072) + HNSW 전환은 별도 Phase.

-- =====================================================================
-- QA 피드백 / 평가 테이블
-- =====================================================================

CREATE TABLE IF NOT EXISTS query_qa_eval (
    id           uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    arch_id      varchar(255) NOT NULL,
    question     text         NOT NULL,
    graph_score  integer,
    vector_score integer,
    created_at   timestamp    NOT NULL DEFAULT now()
);

-- A/B 비교 피드백: queryQaAnswer 응답에서 더 나은 답변(A 또는 B) 선택
CREATE TABLE IF NOT EXISTS query_compare_feedback (
    id              uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    question        text         NOT NULL,
    arch_id         varchar(255) NOT NULL,
    selected_answer varchar(1)   NOT NULL CHECK (selected_answer IN ('A', 'B')),
    answer_a        text         NOT NULL,
    answer_b        text         NOT NULL,
    questioner      varchar(255) NOT NULL,
    response_time   double precision,
    created_at      timestamp    NOT NULL DEFAULT now()
);

-- 단일 응답 평가 피드백: 10점 만점 점수 + 자연어 코멘트
CREATE TABLE IF NOT EXISTS query_rating_feedback (
    id            uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    question      text         NOT NULL,
    arch_id       varchar(255) NOT NULL,
    score         integer      NOT NULL CHECK (score BETWEEN 1 AND 10),
    answer        text         NOT NULL,
    comment       text,
    type          varchar(32)  NOT NULL,
    questioner    varchar(255) NOT NULL,
    response_time double precision,
    created_at    timestamp    NOT NULL DEFAULT now()
);
